baseURL = "https://www.zeko.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Zekeriya Koç"
title = "Zekeriya Koç"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
# googleAnalytics = "UA-160310021-1"
disqusShortname = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["Zekeriya","Koç","Zekeriya Koç", "zekzekus", "zekus"]

	# Add meta description in head part
	description = "Epicenter of Zekeriya Koç's (a.k.a. zekzekus) online presence"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Zekeriya Koç"

	# Add a subtitle to your website
	subtitle = "Epicenter of my online presence"

	# Activate to show authors on pages if available
	listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = ""

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
	mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# Custom CSS applied to default styles. (Path is static/css/)
	customCSS = "custom.css"

# Nav.
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

# [[menu.main]]
# name = "All Posts"
# url = "/post"
# weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

# [[menu.main]]
# name = "Categories"
# url = "/categories"
# weight = 5

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/zekzekus"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
