#+STARTUP: overview
#+HUGO_BASE_DIR: ../

* Home
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_FILE_NAME: _index
:END:
* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** Posts
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_MENU: :menu "main"
:END:
** FP Istanbul 001 ve Sonrası (biraz da öncesi) :@events:fpistanbul:
CLOSED: [2020-03-16 Sun 01:10]
:PROPERTIES:
:EXPORT_FILE_NAME: fp-001
:END:
5 Mart. Perşembe. Yorucu bir haftanın tepe noktasını yeni aşmış, artık yokuş aşağı, kütle çekiminin de desteğiyle akıp, döngüyü nihayetine erdirmek yerine, muhteşem bir boğaz manzarasına kafamı kaldırmış, yağmura dönmek üzere olan kasvetli havaya bakarken, ilk kez organizasyonunun bu kadar içinde olduğum bir etkinliğe kaç kişinin geleceğini kestirmeye çalışıyorum.

İtiraf etmek gerek. Etkinliğe olan yoğun ilgiye biraz hazırlıksız yakalandık. Koltuk sınırını sonradan koyduğumuz için, ofisimize gelenlerin de gördüğü gibi, 120 kişilik bir kapasitemiz yoktu ve içimizde, “ya çok az insan gelirse” ile “ya çok çok insan gelirse” arasında salınan garip bir endişe vardı. Ücretsiz etkinliklerde genel kural kayıt olanların ancak 1/3’ünün gerçekten katılım sağlayacağı yönündedir. Bu bir açıdan rahatlatıcı olsa da [[http://kommunity.com/][kommunity.com]] ekibinden aldığımız bilgi, katılım oranının çok daha yüksek olabileceği yönündeydi ve misafirlerimizi hakkıyla ağırlayamamak ihtimali bizi oldukça endişelendirdi.

Hülasa, gün geldi çattı, hava bozdu, yağmur yağdı ve etkinliğe tam kıvamında, harika bir katılım gerçekleşti. Kayıt olanların yaklaşık yarısı ve kapasitemizin tam yettiği sayıda kıymetli insan. Her birinize kendim ve etkinliğe emek veren tüm arkadaşlarım adına çok teşekkür ediyorum.

Kendi adıma etkinlikte yaptığım mini konuşmada vurgulamaya çalıştığım üzere, fonksiyonel programlamanın belirli bazı dillerden bağımsız değerleri barındırdığını, bu sebeple çok kıymetli olduğunu düşünüyorum. Bunun yanında, o belirli bazı diller üzerinde yapılan çeşitli araştırma geliştirme eforlarının genel programlama ekosistemine büyük katkıları oldu, olmakta ve olmaya da devam edecek.

Benim adıma etkinliğin en keyifli bölümü, sevgili Ertuğrul Çetin'in konuşması sonunda başlayan soru/cevap oturumuydu. Kaliteli sorular ile kitle dahilinde güzel bir etkileşim olduğunu ve bu enerjinin önümüzdeki etkinlikleri de besleyeceğini düşündürttü bana.

Şimdi topluluk olarak hedefimiz bu enerjiyi, devamlılık sağlayarak desteklemek ve birbirine faydası gitgide artan bir grup haline gelmek.

Bağlantıda kalmak için bizi destekleyen (benim da çalışmakta olduğum) Pisano’nun twitter hesabını takip edebilirsiniz ([[https://twitter.com/pisanodev/][@pisanodev]]). Bir sonraki etkinliğimizi nasıl bir formatta yapacağımıza dair fikirlerinizi almak için twitter ve [[http://kommunity.com/][kommunity.com]] aracılığıyla iletişimde olacağız. Yaptığımız etkinlik ile ilgili geri bildirimlerinizi şu[fn:1] adresten iletebileceğinizi de hatırlatmak isterim.

Görüşmek üzere!

[fn:1] https://psn.vc/7ny88gq4t1
** TODO Koşmasaydım yazamazdım                                            :@personal:running:writing:
:PROPERTIES:
:EXPORT_FILE_NAME: kosmasaydim-yazamazdim
:END:
Bugün (25 Temmuz 2020), sabah saat 09:06 ile 09:36 arasında geçen 30 dakika boyunca koştum. Ve şu anda yine bugün (yine 25 Temmuz 2020, ilginç...), saat 22:30 civarı ve bu satırları karalıyorum. Hayır, karalamıyorum. Bir bilgisayarın tuşlarına minik darbeler indiriyorum. İşin bu kısmı çok da mühim değil muhtemelen.

Koşmasaydım eğer, bu satırları da çok büyük ihtimalle yazmıyor olacaktım. Son dönem dünya edebiyatını takip edenler başlıktaki intihali farketmiştir. Hemen yargılamayın. [[https://en.wikipedia.org/wiki/Haruki_Murakami][Haruki Murakami]] anlayışla karşılayacaktır beni. Şunun şurasında koştuğum 5 kilometre, yazdığım bir blog gönderisi. Benim şahsım için önemli zira, dünyanın resmen hop hop hopladığı, büyük acıların, zorlukların yaşandığı bir dönemde de olsa, uzun zamandır yapmadığım bir kaç şeyi yapma fırsatı buldum. Gayet bariz ki koşmak ve yazmak bunlardan ikisi.
* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: about
:END:
** About
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "topmenu"
:END:
About me
