#+STARTUP: overview
#+HUGO_BASE_DIR: ../

* Home
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_FILE_NAME: _index
:END:
* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** Posts
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_MENU: :menu "main"
:END:
** FP Istanbul 001 ve Sonrası (biraz da öncesi) :@events:fpistanbul:
CLOSED: [2020-03-16 Sun 01:10]
:PROPERTIES:
:EXPORT_FILE_NAME: fp-001
:END:
5 Mart. Perşembe. Yorucu bir haftanın tepe noktasını yeni aşmış, artık yokuş aşağı, kütle çekiminin de desteğiyle akıp, döngüyü nihayetine erdirmek yerine, muhteşem bir boğaz manzarasına kafamı kaldırmış, yağmura dönmek üzere olan kasvetli havaya bakarken, ilk kez organizasyonunun bu kadar içinde olduğum bir etkinliğe kaç kişinin geleceğini kestirmeye çalışıyorum.

İtiraf etmek gerek. Etkinliğe olan yoğun ilgiye biraz hazırlıksız yakalandık. Koltuk sınırını sonradan koyduğumuz için, ofisimize gelenlerin de gördüğü gibi, 120 kişilik bir kapasitemiz yoktu ve içimizde, “ya çok az insan gelirse” ile “ya çok çok insan gelirse” arasında salınan garip bir endişe vardı. Ücretsiz etkinliklerde genel kural kayıt olanların ancak 1/3’ünün gerçekten katılım sağlayacağı yönündedir. Bu bir açıdan rahatlatıcı olsa da [[http://kommunity.com/][kommunity.com]] ekibinden aldığımız bilgi, katılım oranının çok daha yüksek olabileceği yönündeydi ve misafirlerimizi hakkıyla ağırlayamamak ihtimali bizi oldukça endişelendirdi.

Hülasa, gün geldi çattı, hava bozdu, yağmur yağdı ve etkinliğe tam kıvamında, harika bir katılım gerçekleşti. Kayıt olanların yaklaşık yarısı ve kapasitemizin tam yettiği sayıda kıymetli insan. Her birinize kendim ve etkinliğe emek veren tüm arkadaşlarım adına çok teşekkür ediyorum.

Kendi adıma etkinlikte yaptığım mini konuşmada vurgulamaya çalıştığım üzere, fonksiyonel programlamanın belirli bazı dillerden bağımsız değerleri barındırdığını, bu sebeple çok kıymetli olduğunu düşünüyorum. Bunun yanında, o belirli bazı diller üzerinde yapılan çeşitli araştırma geliştirme eforlarının genel programlama ekosistemine büyük katkıları oldu, olmakta ve olmaya da devam edecek.

Benim adıma etkinliğin en keyifli bölümü, sevgili Ertuğrul Çetin'in konuşması sonunda başlayan soru/cevap oturumuydu. Kaliteli sorular ile kitle dahilinde güzel bir etkileşim olduğunu ve bu enerjinin önümüzdeki etkinlikleri de besleyeceğini düşündürttü bana.

Şimdi topluluk olarak hedefimiz bu enerjiyi, devamlılık sağlayarak desteklemek ve birbirine faydası gitgide artan bir grup haline gelmek.

Bağlantıda kalmak için bizi destekleyen (benim da çalışmakta olduğum) Pisano’nun twitter hesabını takip edebilirsiniz ([[https://twitter.com/pisanodev/][@pisanodev]]). Bir sonraki etkinliğimizi nasıl bir formatta yapacağımıza dair fikirlerinizi almak için twitter ve [[http://kommunity.com/][kommunity.com]] aracılığıyla iletişimde olacağız. Yaptığımız etkinlik ile ilgili geri bildirimlerinizi şu[fn:1] adresten iletebileceğinizi de hatırlatmak isterim.

Görüşmek üzere!

[fn:1] https://psn.vc/7ny88gq4t1
** Koşmasaydım yazamazdım                                                 :@personal:running:writing:
CLOSED: [2020-07-26 Sun 21:54]
:PROPERTIES:
:EXPORT_FILE_NAME: kosmasaydim-yazamazdim
:END:
Bugün (25 Temmuz 2020). Sabah saat 09:06 ile 09:36 arasında geçen 30 dakika boyunca koştum. Ve şu anda, bugün (yine 25 Temmuz 2020, ilginç...), saat 22:30 civarı ve bu satırları karalıyorum. Hayır, karalamıyorum. Bir bilgisayarın tuşlarına minik darbeler indiriyorum. İşin bu kısmı çok da mühim değil muhtemelen.

Koşmasaydım eğer, bu satırları da çok büyük ihtimalle yazmıyor olacaktım. Bu arada, modern dünya edebiyatını takip edenler başlıktaki intihali farketmişlerdir. Hemen yargılamayın, [[https://en.wikipedia.org/wiki/Haruki_Murakami][Haruki Murakami]] anlayışla karşılayacaktır beni. Şunun şurasında koştuğum 5 kilometre, yazdığım bir blog gönderisi. Benim şahsım için önemli. Zira, dünyanın resmen hop hop hopladığı, büyük acıların, zorlukların yaşandığı bir dönemde de olsa, uzun zamandır yapmadığım birkaç şeyi yapma fırsatı buldum. Gayet bariz ki koşmak ve yazmak bunlardan ikisi.

Pandemi döneminin ilk iki ayı tam bir hayal kırıklığı idi. Öncelikle şanslı olduğumu belirtmem gerekir. İşimi kaybetmedim, maddi problem yaşamadım, çalıştığım firma beni ofise gitmeye zorlamadı. Hatta tam tersi evimden rahatça çalışabilmem için bana ve tüm diğer çalışanlara verebildiği tüm desteği verdi. Teşekkürler sipirmin! [fn:1] Yıllarca gençliğimdeki kadar okuyamamayı, yazamamayı, topluluk için kodlayamamayı zaman yokluğuna bağladım. Ah İstanbul ah, saatlerimi yollarda yemesen var ya ben ne üretken, ne yaratıcı bir adamdım aslında! Bahsi geçen ilk iki ay gösterdi ki pek öyle değilmiş. İki ay boyunca, artık yollarda geçirmediğim günde belki 4 saat nereye gitti açıkçası ben de tam bilmiyorum. Elimde hep telefon vardı ve kuş cıvıltıları[fn:2]. Velhasıl 2 ayın bilançosu: 10 kg. fazladan ağırlık (Dünya gezegeni şartlarında 116kg. ağırlığa ulaşmam demek bu), okunan 1 (yazıyla: bir) kitap, bol miktarda twitter takipçisi (teşekkürler!).

Ve hayatımı değiştirmeye başladım. Öncelikle sabahları mesai saati başlangıcından 10 dakika önce uyanma alışkanlığından kurtuldum. Bu otomatikman geceleri saat 2-3 gibi uyuma alışkanlığını alıp götürdü. Hâlâ tam uygulayamasam da kendime ait zamanları bölmeye çalıştım. Sabahları uyanma ile mesai başlangıcı arası az okuma çok yazma, çocukları uyuttuktan sonra yatana kadar hep okuma biraz not alma olsun dedim. En azından adını koydum. Uygulayabilmek, *plan* denilen kavramın tek olası *değeri* değil. Planı, *yapmanın* da bir *değer* çıktısı var. Duruma biraz mesafeli bakmaya yarıyor. Sakin bir değerlendirme imkanı sağlıyor insana.

Devamında, Ay'da yaklaşık 20kg. olan ağırlığıma bir çözüm buldum. Mucizevi bir yöntem: diyetisyen[fn:3]. Bilimsel yöntemlerle ihtiyacım olan kalori miktarını makro, mikro besinler arasında paylaştırıp, bana listeler vererek günlük beslenmemi düzene sokan bir kişi. Sonuç 8 haftada 15kg. (Dünyada) gibi bir ağırlık kaybı oldu.

Kilo verebilmek genel motivasyonumu iyice artırırken bir yandan işi hızlandırma amacıyla sabahları koşma fikri devreye girdi. Hemen bir iOS uygulaması[fn:4] satın alarak işe başladım. (Evet bir şeyler satın almak da motivasyonumun bir parçası). Uygulamadaki kilo verme hedefli bir programı uygulamaya başladım. Günaşırı koşuyor, her koşu sonrası sosyal medyada var olma ihtiyacıma katkıda bulunuyor, ve garip bir şekilde bir sonraki koşuyu hevesle beklediğimi farketmeye başlıyordum. Çok ama çok uzun zamandır beceremediğim bir şekilde, ilk hevesle kalmayıp tam 5 hafta boyunca toplamda 18 kez sabahları erken saatte belli bir program dahilinde koştum. Yani başladığım bir işi bitirmenin, bir alanda gelişmenin verdiği hazzı öyle unutmuşum ki...

Devam etmeye karar verdim. Uzun yıllardır bir iki post ve bol miktarda tweet haricinde yazı yayınlamadığımı farkettim. Ve yazıyorum! Evet çokça kişisel ve manasız derecede uzun bir yazı oluyor ama olsun. Yazmaya başladım ve bitirdim. Tamamladım. Kapattım. Hayattaki en önemli meleke olabilir mi *bitirmek*? Başarmak değil, denemek de değil. Bitirmek. Belki. Bilmiyorum. Bana ne?

10 kilometrelik yeni bir programa başlıyorum şimdi. 6 hafta sonunda hedefim 10 kilometre koşabilmek. Daha az kişisel, daha teknik, daha faydalı yazılar yazmak da hedeflerim arasında. Bu yazıları desteklemek için yüksek kalitede, düzenli okumak da öyle. Bunun yanına biraz da topluluk için, açık kaynak kodlayabilmek belki eklenir. Kim bilir? Dedim ya, *planı* kurmaktır bazen bizi bitiş çizgisine taşıyan.

[fn:1] https://pisano.co/
[fn:2] https://twitter.com/
[fn:3] https://tr.wikipedia.org/wiki/Diyetisyen
[fn:4] https://www.runtastic.com/
** TODO Koştuğum Halde Yapamadım                                                          :@personal:
:PROPERTIES:
:EXPORT_FILE_NAME: kostugum-halde-yapamadim
:END:
Geçenlerde bir yazı yazdım[fn:1]. Özet geçmek gerekirse, son dönemlerdeki yüksek motivasyonumun kaynaklarından en önemlisi olarak koşmayı göstermiştim. Havalı bir tavırla, ne kadar da müthiş işler başardığımı, kilo verdiğimi, düzenli koşmaya başladığımı ve hatta ilgili yazının varlığından ve başlığından aşikar ki yazmaya bile başladığımı anlattım.

Hey, söylemeyi unutmuşum, sigarayı da bıraktım. Aşağı yukarı 6 ay olmuş olmalı (hmmm, pandemiden önceydi. Yani tüm müthiş özelliklerimi pandemiye bağlayamam. Güzelll...). I'm awesome bitchezzz!

Başlıktan da belli olduğu üzere (lanet olası başlıklar, sürprizi hep açık ediyorlar) buradaki amaç muhteşemliğimi bir kenara bırakmak (zorlu bir erek) ve yapamadıklarımın da bir listesini, en azından, yapmak. Tabii ki başarılarımda olduğu gibi detaylı bir şekilde değil. Basit, kısa bir liste hali en iyisi.

Pandemi döneminin başlarında, evde zorunlu kalmanın ilk şoku azaldığında misal, **Kitap ciltleme/tamiri** hevesimi canlandırmaya çalıştım. İnternetin bu kadar yaygın ve rahat erişilmediği zamanlarda 10 USD harcayıp elde ettiğim iki tane MS Word dosyası vardı elimde. Pek bir işe yaramadılar. Youtube üzerinden birkaç video izledim ve evet, hayatımın hobisi bunca yıl beklemeden sonra artık benimdi. Hemen sipariş verdim (iflah olmaz bir tüketim bağımlısı olduğumdan bahsetmiş miydim?). Bir kesme matı, mücellit tutkalı, havalı bir kesici malzeme (maket bıçağının havalısı işte). Mallar geldi, ilk iş paylaşımımı yaptım[fn:2] (iflah olmaz bir sosyal medya bağımlısı olduğumdan bahsetmiş miydim?). Sonuç: olmadı. Bir adım ileri gidemedim. Kesim işlemlerini beceremedim ve daha pahalı ekipman satın alma dürtüme karşı koydum. Hayatımın hobisi mi? Saçmalık.

Sonra evde ekmek yapmak istedim. Yaptım da. Çok güzel olmadı. Çok kötü de olmadı. Denemeye devam ederek kaliteyi yükseltebilirdim. Ama yani, zaten birden 10kg. almama sebep olan şeylerden biriydi. Üşendiğim için pişman değilim.

Yanlış hatırlamıyorsam son olarak, yine twitter üzerinden duyurduğum[fn:3] tasarım öğrenme merakı geldi. Sosyal medyada teşhir? check! , Erkenden harcama? check! Sağ olsunun iyi niyetli dostlar bir sürü kaynak gösterdiler, yardımcı oldular. Gerçekçi bir grup, ya hiç bulaşma senlik değil dediler[fn:4]. Ben ise hemen Udemy kursumu satın alıp figma hesabımı oluşturdum. Kursun 3. videosunun boynu halen bükük. Twitter ahalisi allahtan yüzüme vurmuyor bu rezilliği. Paint'i hâlâ Figma'dan iyi bildiğimi kimse bilmiyor diye şükrediyorum.

Velhasıl, yaptıklarımız, yapacaklarımızın teminatı olabileceği gibi, yapamadıklarımızın özürleri ya da sonuçları da olabilir pekala. Çok takılmadan kendini, keyfini aramakta sorun yok. Evet, entelektüel kapasiteme bir işaretçi bırakayım şuraya da beni öyle sırf yazmış olmak için yazan biri zannetmesinler:

#+BEGIN_QUOTE
Quaerendo Invenietis!
#+END_QUOTE

[fn:1] https://zeko.dev/posts/kosmasaydim-yazamazdim/
[fn:2] https://twitter.com/zekzekus/status/1251461532170543104
[fn:3] https://twitter.com/zekzekus/status/1243900100000309248
[fn:4] https://twitter.com/ayadem/status/1243974453572272128
* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: about
:END:
** About
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "topmenu"
:END:
About me
